### PR TITLE
Added login endpoint

### PR DESCRIPTION
**Pull request by MMojtaba**
Feel free to let me know if anything should be changed or any function should be placed in a differnt folder (specfically if the login should be placed in the user files).

### CODE REVIEW

**Comment by MMojtaba** [comment]
Looks like the lint and prettier checks failed, I will look into it.
This is the logic this code is using for login, let me know if any part of it should be changed:
-Server receives a post request at the login endpoint with username and password in the body in json format.
-Server checks if the user and pass exist in the database, and if so, it returns a JWT token.

**Comment by MMojtaba** [comment]
Fixed the checks not passing.

**Review by KjartanE — DISMISSED** [review]
Looks fantastic, great work! 🐈

**Review by KjartanE — APPROVED** [review]
😹

**Pull request merged**
