### PR TITLE
Frontend integration1

### PR DESCRIPTION
**Pull request by MMojtaba**
Might be good to merge now to make future merge of frontend integration easier.

### CODE REVIEW

**Comment by MMojtaba** [comment]
Resolving conflicts.

**Comment by MMojtaba** [comment]
Fixed conflicts. Tested I think all frontend endpoints and they were working.

**Review by ChrisMWest — DISMISSED** [review]

**Comment by Gavinok** [comment]
@MMojtaba is it possible to resolve these broken tests?

**Comment by MMojtaba** [comment]
> @MMojtaba is it possible to resolve these broken tests?

Yeah, my bad, didn't see the tests were failing.

**Review by Gavinok — DISMISSED** [review]
lgtm

**Review by Gavinok — DISMISSED** [review]

**Review by ChrisMWest — DISMISSED** [review]
As far as I can tell it looks good!

**Review by ChrisMWest — DISMISSED** [review]
one more try

**Review by potentstew — DISMISSED** [review]

**Pull request merged**
