### PR TITLE
Added Codecov to mocha

### PR DESCRIPTION
**Pull request by MMojtaba**
Seems to be working; it shows the test cases that failed and the coverage, but failes because test cases failed, so I think it's ok. Let me know if it's a problem.

### CODE REVIEW

**Comment by MMojtaba** [comment]
image

**Comment by MMojtaba** [comment]
After setting all expects to true, doesn't seem to upload the results. Working on a fix.

**Comment by MMojtaba** [comment]
Issues should be fixed now. Let me know if anything needs changing.

**Review by KjartanE — APPROVED** [review]
😸 Great work

**Pull request merged**
